server:
  port: 29001

web:
  client:
    interface-info-url: http://127.0.0.1:8090

module:
  register-prop:
    batch-task: DBPollingAndSend
    interface-list:
      - IF_TEST_01

spring:
  profiles:
    active: local
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  mustache:
    check-template-location: false