server:
  port: 29100

web:
  client:
    interface-info-url: http://127.0.0.1:29010
    gateway-url: http://127.0.0.1:29000

adaptor:
  type: DB
  module-config:
    system-code: COM

spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mustache.MustacheAutoConfiguration
      - org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      