server:
  port: 29000

adaptor:
  type: GATEWAY

spring:
  cloud:
    gateway:
      routes:
        - id: SAP-RFC-RECV
          uri: http://localhost:8090   # 대상 서비스 URI
          predicates:
            - Path=/esb/api/gateway/sap/*   # 요청 경로 조건
          filters:
            - name : CommonRewritePath
#        - id: SAP-RFC-CALL-SYNC
#          uri: http://localhost:8090   # 대상 서비스 URI
#          predicates:
#            - Path=/esb/api/gateway/sap/rfc-call-sync   # 요청 경로 조건
#          filters:
#            - name : CommonRewritePath					
        - id: PCB-DB-PROCESS
          uri: http://localhost:8081   # 대상 서비스 URI
          predicates:
            - Path=/esb/api/gateway/pcb/db-process   # 요청 경로 조건
          filters:
            - name : CommonRewritePath
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration
      - org.springframework.boot.autoconfigure.mustache.MustacheAutoConfiguration